# Tensor Flow Basics

## Tensor Is Basically An 3D Array Of Array

1.   Vecotr         => 1D
2.   Metrix / Array => 2D
3.   Tensore        => 3D


### We Have Vecotor Which is 1D => 1 row or column u say

### And Matrix Or Array which is =>  2D (4,3) which is 4 row and 3 colums

### Tensor Which Have => 3D Means (4,3,2) ** ...pillos or Row of array 4 ..3 Rows ... 2 Columns

**Import Tensor Flow As tf**

In [1]:
import tensorflow as tf

In [2]:
zero_d_tensor=tf.constant(1)
print(zero_d_tensor)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
one_d_tensor=tf.constant([0,1,2,3])
print(one_d_tensor)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [5]:
two_d_tensor=tf.constant(
    [
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11],
    ])
print(two_d_tensor)

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)


In [7]:
three_d_tensor=tf.constant(
    [
        [[0,1,3],[0,2,4]],
        [[10,11,13],[10,12,14]],
        [[20,21,23],[20,22,24]]
    ]
)
print(three_d_tensor)

tf.Tensor(
[[[ 0  1  3]
  [ 0  2  4]]

 [[10 11 13]
  [10 12 14]]

 [[20 21 23]
  [20 22 24]]], shape=(3, 2, 3), dtype=int32)


In [11]:
four_d_tensor=tf.constant(
    [
        [
        [[0,1,3],[0,2,4]],
        [[10,11,13],[10,12,14]],
        [[20,21,23],[20,22,24]]
        ],
        [
        [[0,-1,-3],[0,-2,-4]],
        [[-10,-11,-13],[-10,-12,-14]],
        [[-20,-21,-23],[-20,-22,-24]]
        ],
    ]
)
print(four_d_tensor.ndim)

4


# Defining Data Types

Ether Int Or Float

In [12]:
dtype_one_d_tensor=tf.constant([0,1,2,3],dtype=tf.float16)
print(dtype_one_d_tensor)

tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float16)


**for Reducing Error We Use Higher Precesion**
<div>While For Faster Computation We use Lower Precesions</div

**Type Casting In Tensor Flow**

In [16]:
one_d_tensor=tf.constant([0,1.5,2,3],dtype=tf.float16)
print(one_d_tensor)
# Casting In Tensore Flow
casted_one_d_tensor=tf.cast(one_d_tensor,tf.int32)
print(casted_one_d_tensor)

tf.Tensor([0.  1.5 2.  3. ], shape=(4,), dtype=float16)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
