In [1]:
import tensorflow as tf

In [5]:
two_d_tensor=tf.constant(
    [
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11],
    ]
    )

In [16]:
print(two_d_tensor[0:3,1:])

tf.Tensor([7 8], shape=(2,), dtype=int32)


In [17]:
print(two_d_tensor[2,:])

tf.Tensor([6 7 8], shape=(3,), dtype=int32)


In [18]:
print(two_d_tensor[...,1:])

tf.Tensor(
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]], shape=(4, 2), dtype=int32)
