In [1]:
import tensorflow as tf

In [2]:
print(tf.abs(tf.constant([-1,0,-1])))

tf.Tensor([1 0 1], shape=(3,), dtype=int32)


In [3]:
print(tf.square(tf.constant([4,2])))

tf.Tensor([16  4], shape=(2,), dtype=int32)


In [7]:
nums_list_one=tf.constant([4,2,4])
nums_list_two=tf.constant([4,2,4])

print(tf.add(nums_list_one,nums_list_two))
print(tf.subtract(nums_list_one,nums_list_two))
print(tf.divide(nums_list_one,nums_list_two))
print(tf.multiply(nums_list_one,nums_list_two))

tf.Tensor([8 4 4], shape=(3,), dtype=int32)
tf.Tensor([0 0 4], shape=(3,), dtype=int32)
tf.Tensor([ 1.  1. inf], shape=(3,), dtype=float64)
tf.Tensor([16  4  0], shape=(3,), dtype=int32)


In [11]:
print(nums_list_two)
print(tf.math.divide_no_nan(nums_list_one,nums_list_two))

tf.Tensor([4 2 0], shape=(3,), dtype=int32)
tf.Tensor([1. 1. 0.], shape=(3,), dtype=float64)


In [14]:
row_d_tensor=tf.constant([[1,2,3,4]])
col_d_tensor=tf.constant([[1],[2],[3],[4]])
print(row_d_tensor.shape)
print(col_d_tensor.shape)
print(tf.math.multiply(row_d_tensor,col_d_tensor))

(1, 4)
(4, 1)
tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]], shape=(4, 4), dtype=int32)


In [25]:
row_one_tensor=tf.constant([-5,-2,0,2.0,5])
row_two_tensor=tf.constant([0,3,-5,0,8])

In [17]:
print(tf.math.maximum(row_one_tensor,row_two_tensor))

tf.Tensor([0 3 0 2 8], shape=(5,), dtype=int32)


In [18]:
print(tf.math.minimum(row_one_tensor,row_two_tensor))

tf.Tensor([-5 -2 -5  0  5], shape=(5,), dtype=int32)


In [19]:
print(tf.math.equal(row_one_tensor,row_two_tensor))

tf.Tensor([False False False False False], shape=(5,), dtype=bool)


In [26]:
print(tf.math.sigmoid(row_one_tensor))

tf.Tensor([0.00669285 0.11920292 0.5        0.8807971  0.9933072 ], shape=(5,), dtype=float32)
